### ISSUE TITLE
Add command line suggestions when lyric is not found

### ISSUE THREAD

**Issue by collinsnji** [collinsnji/Furler#1]
Currently, when a lyric is not found, it simple returns and error message (Lyric not found). Add cli suggestions for lyrics.

For example if I enter: `furler The Greatst - Sia`, this should return `Lyric not found :(. Did you mean 'The Greatest - Sia'`

**Comment by phocks** [comment]
It might be difficult to get song suggestions just from scraping the atoz lyrics website. I'd probably try using an API like the Genius API https://docs.genius.com/#search-h2

Or maybe it would be feasible to have a local database of the top most popular songs and build a fuzzy search from that. I may have some time to work on this a bit perhaps sometime during Hacktoberfest :)

**Comment by collinsnji** [comment]
I thought about using the Genius API, but I don't want to deal with API keys. Feel free to work on this anytime

**Comment by collinsnji** [comment]
Issue has been fixed by: #2
